javase/src/main/java/org/jcodec/scale/AWTUtil.java

Fixed apparent copy/paste bug in AWTUtil.fromBufferedImage

---

android/src/main/org/jcodec/api/android/SequenceMuxer.java
extras/pom.xml
extras/src/main/java/org/jcodec/extras/streaming/FFMpegAACTrack.java

makes `android` and `extras` sub projects at least compile without error

make android and extras compile

---

README.md

Welcome project that was very handy in solving an immediate need, however the examples given did not work with either the referenced, aged 0.1.9 version, or with the current version as built.

Updating basic readme examples for revised API

---

src/main/java/org/jcodec/api/transcode/Transcoder.java

Fixing some of the transcoder bugs.

[xcode] Fixing video-only case, color transform case.

---

src/test/java/org/jcodec/api/Issue136Test.java

tests https://github.com/jcodec/jcodec/issues/136

Issue136Test

---

src/test/java/org/jcodec/api/Issue180Test.java

make sure https://github.com/jcodec/jcodec/issues/180 is fixed

test issue 180

---

src/test/java/org/jcodec/codecs/h264/H264EncoderTest.java

this PR tests https://github.com/jcodec/jcodec/issues/231

test for #231

---

src/main/java/org/jcodec/api/transcode/TranscodeMain.java
src/main/java/org/jcodec/api/transcode/Transcoder.java
src/main/java/org/jcodec/api/transcode/filters/ColorTransformFilter.java
src/main/java/org/jcodec/api/transcode/filters/ScaleFilter.java
src/main/java/org/jcodec/common/model/ColorSpace.java
src/main/java/org/jcodec/common/model/Picture.java

Scale filter based on Lanczos filter implementation, plus command line tool support.

Scale filter

---

src/main/java/org/jcodec/containers/mp4/BoxFactory.java
src/main/java/org/jcodec/containers/mp4/DefaultBoxes.java
src/main/java/org/jcodec/containers/mp4/boxes/DataBox.java
src/main/java/org/jcodec/containers/mp4/boxes/Header.java
src/main/java/org/jcodec/containers/mp4/boxes/IListBox.java
src/main/java/org/jcodec/containers/mp4/boxes/KeysBox.java
src/main/java/org/jcodec/containers/mp4/boxes/MdtaBox.java
src/main/java/org/jcodec/containers/mp4/boxes/MetaBox.java
src/main/java/org/jcodec/containers/mp4/boxes/MetaValue.java
src/main/java/org/jcodec/containers/mp4/boxes/NodeBox.java
src/main/java/org/jcodec/containers/mp4/boxes/UdtaBox.java
src/main/java/org/jcodec/containers/mp4/boxes/UdtaMetaBox.java
src/main/java/org/jcodec/platform/Platform.java

This is needed to support metadata editor in a separate PR

[mp4] udta,meta,ilst,mdta,keys,data boxes

---

src/main/java/org/jcodec/movtool/Flattern.java

Flattern used to not store the final mdat size making the movie invalid. While here making the code a little prettier.

[mp4] Flattern bug

---

pom.xml
src/main/java/org/jcodec/common/tools/MainUtils.java
src/main/resources/git.properties

Main utils will attempt to automatically output the git version the jar was built.

[misc] Git revision support

---

pom.xml
src/main/java/org/jcodec/common/tools/MainUtils.java

Also print JCodec version from the command line tools.

[main util] Print JCodec version

---

.travis.yml

https://travis-ci.org/chexov/jcodec

Run tests and get PR+tests satus using travis-ci org

---

src/main/java/org/jcodec/codecs/h264/H264Utils.java
src/test/java/org/jcodec/codecs/h264/H264UtilsTest.java

critical for old phones like motorola xt1053

~3x faster nal unit search

---

src/main/java/org/jcodec/common/dct/SimpleIDCT10Bit.java
src/test/java/org/jcodec/codecs/prores/ProresEncoderTest.java

Just came across float implementation of FDCT in Prores, changing that to int.

[prores_enc] Int fdct

---

README.md
src/main/java/org/jcodec/containers/mp4/boxes/UdtaBox.java
src/test/java/org/jcodec/containers/mp4/AppleGpsTest.java

parse gps from files provided in #372

parse gps from mp4 test

---

README.md
src/main/java/org/jcodec/containers/mkv/demuxer/MKVDemuxer.java
src/test/java/org/jcodec/containers/mkv/MkvExtractSubsTest.java

extract mkv subs

---

README.md

0.2.3 has issues when used for meta data in Android. This version bump would help people locate the fixed version of the library. Great library though. Thanks y'all!

Update: version to 0.2.5 in README.md

---

pom.xml
src/main/java/org/jcodec/codecs/h264/io/model/NALReasemble.java
src/main/java/org/jcodec/codecs/h264/io/model/NALUnitType.java
src/test/java/org/jcodec/codecs/h264/io/model/NALReassembleTest.java
src/test/java/org/jcodec/codecs/h264/io/model/NalUnitTest.java
src/test/java/org/jcodec/codecs/h264/io/model/NalUnitTypeTest.java

Resolves Issue #427 
Also adds some unit tests for NAL related items, and fully tested NAL reassembly.
Also introduces test coverage tool into build

Fu a defragment - fixes issue #427

---

samples/main/java/org/jcodec/samples/mux/MKVDemux.java
src/main/java/org/jcodec/common/Codec.java
src/main/java/org/jcodec/common/model/Size.java
src/main/java/org/jcodec/containers/mkv/MKVType.java
src/main/java/org/jcodec/containers/mkv/demuxer/MKVDemuxer.java
src/test/java/org/jcodec/containers/mkv/AudioTrackTest.java
src/test/java/org/jcodec/containers/mkv/BlockOrderingTest.java
src/test/java/org/jcodec/containers/mkv/MKVDemuxerTest.java
src/test/java/org/jcodec/containers/mkv/MKVFrameReadingTest.java
src/test/java/org/jcodec/containers/mkv/MKVMuxerTest.java
src/test/java/org/jcodec/containers/mkv/MKVParserTest.java
src/test/java/org/jcodec/containers/mkv/MkvBlockTest.java
src/test/java/org/jcodec/containers/mkv/WEBMDemuxerTest.java

Hello
I update all the MKVType for the v4 of matrovska ( & update all comments)
I add in the MKV demuxer the code to permit to list the tracks in the file (for audo: nb channels, language and codec)
I add OPUS in the list of codec
I add a simple example of the MKV demuxer (will update later)
Best regards
Edouard DUPIN

Update Matrovska demuxer and v4 types

---

src/main/java/org/jcodec/codecs/vpx/VP8Encoder.java
src/main/java/org/jcodec/containers/mkv/CuesFactory.java
src/main/java/org/jcodec/containers/mkv/boxes/EbmlDate.java
src/main/java/org/jcodec/containers/mkv/muxer/MKVMuxer.java
src/main/java/org/jcodec/containers/mkv/muxer/MKVMuxerTrack.java
src/main/java/org/jcodec/platform/Platform.java

- MKV headers were having timing issues all around
- MKV did not support multiple frame rates (25 was practically all you
could do)
- VP8 is now working as per rafcsoares's solution from #420

MKV header fixes + VP8 support (based on the code from rafcsoares)
